[build-system]
requires = [
    "param >=1.9.2",
    "pyct >=0.4.4",
    "setuptools >=42",
    "bokeh >=2.4.3,<2.5.0",
    "pyviz_comms >=0.7.4",
    "requests",
    "bleach",
    "packaging",
    "tqdm >=4.48.0"
]
