name: docs

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
      - 'v[0-9]+.[0-9]+.[0-9]+a[0-9]+'
      - 'v[0-9]+.[0-9]+.[0-9]+b[0-9]+'
      - 'v[0-9]+.[0-9]+.[0-9]+rc[0-9]+'
  workflow_dispatch:
    inputs:
      target:
        description: 'Site to build and deploy'
        type: choice
        options:
        - dev
        - main
        - dryrun
        required: true
        default: dryrun
  schedule:
    - cron: '0 19 * * SUN'

jobs:
  build_docs:
    name: Documentation
    runs-on: 'ubuntu-latest'
    timeout-minutes: 120
    defaults:
      run:
        shell: bash -l {0}
    env:
      DESC: "Documentation build"
      MPLBACKEND: "Agg"
      SETUPTOOLS_ENABLE_FEATURES: "legacy-editable"
      MOZ_HEADLESS: 1
      DISPLAY: ":99.0"
      PANEL_IPYWIDGET: 1
    steps:
      - name: remove nodejs
        run: |
          sudo rm /usr/local/bin/node
          sudo rm /usr/local/bin/npm
      - uses: actions/checkout@v3
        with:
          fetch-depth: "100"
      - uses: conda-incubator/setup-miniconda@v2
        with:
          miniconda-version: "latest"
      - name: Fetch unshallow
        run: git fetch --prune --tags --unshallow -f
      - name: Set and echo git ref
        id: vars
        run: |
          echo "Deploying from ref ${GITHUB_REF#refs/*/}"
          echo ::set-output name=tag::${GITHUB_REF#refs/*/}
      - name: conda setup
        run: |
          conda update -n base -c defaults conda
          conda create -n test-environment
          conda activate test-environment
          conda config --remove channels defaults
          conda config --env --remove channels defaults
          conda config --env --append channels pyviz/label/dev --append channels bokeh --append channels conda-forge
          conda install python=3.9 pyctdev
      - uses: actions/setup-node@v2
        with:
          node-version: '15'
      - name: doit develop_install and other installs
        run: |
          conda activate test-environment
          doit develop_install -o examples -o doc
          pip install --use-deprecated=legacy-resolver pyecharts "idom==0.24" "pydata-sphinx-theme<=0.9.0" "pydata-sphinx-theme<=0.9.0" sphinx-copybutton sphinx-design
      - name: doit env_capture
        run: |
          conda activate test-environment
          doit env_capture
      - name: opengl
        run: |
          sudo apt-get install libglu1-mesa
          conda install -c conda-forge mesalib --no-update-deps
          /sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x24
          sleep 3
      - name: bokeh sampledata
        run: |
          conda activate test-environment
          bokeh sampledata
      - name: generate rst
        run: |
          conda activate test-environment
          nbsite generate-rst --org holoviz --project-name panel
      - name: refmanual
        run: |
          conda activate test-environment
          python ./doc/generate_modules.py panel -d ./doc/api -n panel -e tests
      - name: build docs
        run: |
          conda activate test-environment
          nbsite build --what=html --output=builtdocs --org holoviz --project-name panel
          cp -r ./panel/dist ./builtdocs/panel_dist
      - name: convert gallery
        run: |
          conda activate test-environment
          panel convert examples/gallery/**/*.ipynb --to pyodide-worker --out ./builtdocs/pyodide/ --pwa --index
      - name: git status and git diff
        run: |
          git status
          git diff
      - name: Deploy dev
        uses: peaceiris/actions-gh-pages@v3
        if: |
          (github.event_name == 'workflow_dispatch' && github.event.inputs.target == 'dev') ||
          (github.event_name == 'push' && (contains(steps.vars.outputs.tag, 'a') || contains(steps.vars.outputs.tag, 'b') || contains(steps.vars.outputs.tag, 'rc')))
        with:
          personal_token: ${{ secrets.ACCESS_TOKEN }}
          external_repository: pyviz-dev/panel
          publish_dir: ./builtdocs
          force_orphan: true
      - name: Deploy main
        if: |
          (github.event_name == 'workflow_dispatch' && github.event.inputs.target == 'main') ||
          (github.event_name == 'push' && !(contains(steps.vars.outputs.tag, 'a') || contains(steps.vars.outputs.tag, 'b') || contains(steps.vars.outputs.tag, 'rc')))
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./builtdocs
          cname: panel.holoviz.org
          force_orphan: true
  deploy_jupyterlite:
    name: JupyterLite
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install the dependencies
        run: |
          python -m pip install -r ./lite/requirements.txt
      - name: Build pyodide wheels for JupyterLite
        run: |
          python ./scripts/build_pyodide_wheels.py lite/pypi
      - name: Convert content
        run: |
          python ./scripts/generate_panelite_content.py
      - name: Build the JupyterLite site
        run: |
          jupyter lite build --lite-dir lite --output-dir lite/dist
      - name: upload
        if: |
          (github.event_name == 'workflow_dispatch' && github.event.inputs.target == 'main') ||
          (github.event_name == 'push' && !(contains(steps.vars.outputs.tag, 'a') || contains(steps.vars.outputs.tag, 'b') || contains(steps.vars.outputs.tag, 'rc')))
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.ACCESS_TOKEN }}
          external_repository: pyviz-dev/panelite
          publish_dir: ./lite/dist
          cname: panelite.holoviz.org
          force_orphan: true
